version: '3'
services:
  fizzbuzz_service:
    build:
      context: .
      dockerfile: dockerfile
    image: fizzbuzz_image
    container_name: container_fizzbuzz
    ports:
      - "5000:5000"
    links:
      - mysql_server
#    networks:
#      - mysql-compose-network
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: "testedb"
      MYSQL_USER: "userteste"
    ports:
      - "3306:3306"
#    networks:
#      - mysql-compose-network
#
#networks:
#  mysql-compose-network:
#    driver: bridge